controller_manager:
  ros__parameters:
    update_rate: 10
    
    # Joint Trajectory Controller
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - head_Revolute_25
      - head_Revolute_26
      - head_Revolute_27 
      - head_Revolute_34
      - head_Revolute_36
      - head_Revolute_37
      - head_Revolute_38
      - head_Revolute_44
      - head_Revolute_45
      - head_Revolute_46
      - head_Revolute_47
      - head_Revolute_48
      - head_Revolute_54
      - head_Revolute_55
      - head_Revolute_56
      - head_Revolute_57
      - head_Revolute_58
      - head_Revolute_64
      - head_Revolute_65
      - head_Revolute_66
      - head_Revolute_67
      - head_Revolute_68
      - head_Revolute_74
      - head_Revolute_75
      - head_Revolute_76
      - head_Revolute_77
      - head_Revolute_78
      - head_Revolute_84
      - head_Revolute_85
      - head_Slider_30
      - head_Slider_40
      - head_Slider_50
      - head_Slider_60
      - head_Slider_70
      - head_Slider_80

    command_interfaces:
      - position
    
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
