controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Joint Trajectory Controller
    stewart_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    stewart_platform_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    stewart_slider_controller:
      type: position_controllers/JointGroupPositionController

    # right_hand_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController
    
    # left_hand_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # waist_joint_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # right_leg_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    # left_leg_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    right_hand_joints_controller:
      type: position_controllers/JointGroupPositionController

    right_hand_elbow_controller:
      type: position_controllers/JointGroupPositionController

    left_hand_joints_controller:
      type: position_controllers/JointGroupPositionController

    left_hand_elbow_controller:
      type: position_controllers/JointGroupPositionController

    waist_joints_controller:
      type: position_controllers/JointGroupPositionController
      
    right_leg_knee_controller:
      type: position_controllers/JointGroupPositionController

    lower_right_leg_controller:
      type: position_controllers/JointGroupPositionController

    left_leg_knee_controller:
      type: position_controllers/JointGroupPositionController

    lower_left_leg_controller:
      type: position_controllers/JointGroupPositionController

stewart_base_controller:
  ros__parameters:
    joints:
      - head_Revolute25
      - head_Revolute26
      - head_Revolute27 
      - head_Revolute36
      - head_Revolute37
      - head_Revolute38
      - head_Revolute46
      - head_Revolute47
      - head_Revolute48
      - head_Revolute56
      - head_Revolute57
      - head_Revolute58
      - head_Revolute66
      - head_Revolute67
      - head_Revolute68
      - head_Revolute76
      - head_Revolute77
      - head_Revolute78

    command_interfaces:
      - position
    
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

stewart_slider_controller:
  ros__parameters:
    joints:
      - head_Slider30
      - head_Slider40
      - head_Slider50
      - head_Slider60
      - head_Slider70
      - head_Slider80

    command_interfaces:
      - position
    
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

stewart_platform_controller:
  ros__parameters:
    joints:
      - head_Revolute34
      - head_Revolute44
      - head_Revolute45
      - head_Revolute54
      - head_Revolute55
      - head_Revolute64
      - head_Revolute65
      - head_Revolute74
      - head_Revolute75
      - head_Revolute84
      - head_Revolute85


    command_interfaces:
      - position
    
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


right_hand_joints_controller:
  ros__parameters:
    joints:
      - RH_yaw
      - RH_pitch
      - RH_roll
      - RH_wrist_roll

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


right_hand_elbow_controller:
  ros__parameters:
    joints:
      - RH_elbow_joint
      - RH_Revolute32
      - RH_Revolute33
      - RH_Revolute41
      - RH_Revolute42
      - RH_Revolute44

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

left_hand_joints_controller:
  ros__parameters:
    joints:
      - LH_yaw
      - LH_pitch
      - LH_roll
      - LH_wrist_roll

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


left_hand_elbow_controller:
  ros__parameters:
    joints:
      - LH_elbow_joint
      - LH_Revolute32
      - LH_Revolute33
      - LH_Revolute41
      - LH_Revolute42
      - LH_Revolute44

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

waist_joints_controller:
  ros__parameters:
    joints:
      - PG_left_leg_roll
      - PG_left_leg_pitch
      - PG_right_leg_roll
      - PG_right_leg_pitch
      - PG_Revolute31
      - PG_Revolute32
      - PG_Revolute33
      - PG_Revolute34


    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


right_leg_knee_controller:
  ros__parameters:
    joints:
      - RL_hip_joint
      - RL_knee_actuator_joint
      - RL_Revolute28
      - RL_Revolute29
      - RL_Revolute33
      - RL_Revolute34
      - RL_Revolute37
      - RL_Revolute38
      - RL_Revolute46
      - RL_Revolute47
      - RL_Revolute48
      - RL_Revolute49

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


lower_right_leg_controller:
  ros__parameters:
    joints:
      - RL_Revolute67
      - RL_Revolute81
      - RL_Revolute87
      - RL_Revolute88
      - RL_Revolute89
      - RL_Revolute111
      - RL_Revolute112

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true


left_leg_knee_controller:
  ros__parameters:
    joints:
      - LL_hip_joint
      - LL_knee_actuator_joint
      - LL_Revolute28
      - LL_Revolute29
      - LL_Revolute33
      - LL_Revolute34
      - LL_Revolute37
      - LL_Revolute38
      - LL_Revolute46
      - LL_Revolute47
      - LL_Revolute48
      - LL_Revolute49

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true



lower_left_leg_controller:
  ros__parameters:
    joints:
      - LL_Revolute67
      - LL_Revolute81
      - LL_Revolute87
      - LL_Revolute88
      - LL_Revolute89
      - LL_Revolute111
      - LL_Revolute112

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

