# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
GProp module, see official documentation at
https://www.opencascade.com/doc/occt-7.4.0/refman/html/package_gprop.html
"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _GProp.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_GProp')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_GProp')
    _GProp = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GProp', [dirname(__file__)])
        except ImportError:
            import _GProp
            return _GProp
        try:
            _mod = imp.load_module('_GProp', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _GProp = swig_import_helper()
    del swig_import_helper
else:
    import _GProp
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GProp.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_GProp.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_GProp.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_GProp.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_GProp.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_GProp.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_GProp.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_GProp.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_GProp.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_GProp.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_GProp.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_GProp.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_GProp.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_GProp.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_GProp.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_GProp.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_GProp.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _GProp.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string


def process_exception(error: 'Standard_Failure const &', method_name: 'std::string', class_name: 'std::string') -> "void":
    return _GProp.process_exception(error, method_name, class_name)
process_exception = _GProp.process_exception

from six import with_metaclass
import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

import OCC.Core.Standard
import OCC.Core.NCollection
import OCC.Core.gp
import OCC.Core.TColgp
import OCC.Core.TColStd
import OCC.Core.TCollection
GProp_Plane = _GProp.GProp_Plane
GProp_Line = _GProp.GProp_Line
GProp_Point = _GProp.GProp_Point
GProp_Space = _GProp.GProp_Space
GProp_None = _GProp.GProp_None
GProp_Mass = _GProp.GProp_Mass
GProp_CenterMassX = _GProp.GProp_CenterMassX
GProp_CenterMassY = _GProp.GProp_CenterMassY
GProp_CenterMassZ = _GProp.GProp_CenterMassZ
GProp_InertiaXX = _GProp.GProp_InertiaXX
GProp_InertiaYY = _GProp.GProp_InertiaYY
GProp_InertiaZZ = _GProp.GProp_InertiaZZ
GProp_InertiaXY = _GProp.GProp_InertiaXY
GProp_InertiaXZ = _GProp.GProp_InertiaXZ
GProp_InertiaYZ = _GProp.GProp_InertiaYZ
GProp_Unknown = _GProp.GProp_Unknown
class gprop(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def HOperator(*args) -> "void":
        """
        * methods of package Computes the matrix Operator, referred to as the 'Huyghens Operator' of a geometric system at the point Q of the space, using the following data : - Mass, i.e. the mass of the system, - G, the center of mass of the system. The 'Huyghens Operator' is used to compute Inertia/Q, the matrix of inertia of the system at the point Q using Huyghens' theorem : Inertia/Q = Inertia/G + HOperator (Q, G, Mass) where Inertia/G is the matrix of inertia of the system relative to its center of mass as returned by the function MatrixOfInertia on any GProp_GProps object.
        	:param G:
        	:type G: gp_Pnt
        	:param Q:
        	:type Q: gp_Pnt
        	:param Mass:
        	:type Mass: float
        	:param Operator:
        	:type Operator: gp_Mat
        	:rtype: void
        """
        return _GProp.gprop_HOperator(*args)

    HOperator = staticmethod(HOperator)

    __repr__ = _dumps_object


    def __init__(self):
        _GProp.gprop_swiginit(self, _GProp.new_gprop())
    __swig_destroy__ = _GProp.delete_gprop
gprop_swigregister = _GProp.gprop_swigregister
gprop_swigregister(gprop)

def gprop_HOperator(*args) -> "void":
    """
    * methods of package Computes the matrix Operator, referred to as the 'Huyghens Operator' of a geometric system at the point Q of the space, using the following data : - Mass, i.e. the mass of the system, - G, the center of mass of the system. The 'Huyghens Operator' is used to compute Inertia/Q, the matrix of inertia of the system at the point Q using Huyghens' theorem : Inertia/Q = Inertia/G + HOperator (Q, G, Mass) where Inertia/G is the matrix of inertia of the system relative to its center of mass as returned by the function MatrixOfInertia on any GProp_GProps object.
    	:param G:
    	:type G: gp_Pnt
    	:param Q:
    	:type Q: gp_Pnt
    	:param Mass:
    	:type Mass: float
    	:param Operator:
    	:type Operator: gp_Mat
    	:rtype: void
    """
    return _GProp.gprop_HOperator(*args)

class GProp_GProps(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Either - initializes the global properties retained by this framework from those retained by the framework Item, or - brings together the global properties still retained by this framework with those retained by the framework Item. The value Density, which is 1.0 by default, is used as the density of the system analysed by Item. Sometimes the density will have already been given at the time of construction of the framework Item. This may be the case for example, if Item is a GProp_PGProps framework built to compute the global properties of a set of points ; or another GProp_GProps object which already retains composite global properties. In these cases the real density was perhaps already taken into account at the time of construction of Item. Note that this is not checked: if the density of parts of the system is taken into account two or more times, results of the computation will be false. Notes : - The point relative to which the inertia of Item is computed (i.e. the reference point of Item) may be different from the reference point in this framework. Huygens' theorem is applied automatically to transfer inertia values to the reference point in this framework. - The function Add is used once per component of the system. After that, you use the interrogation functions available to access values computed for the system. - The system whose global properties are already brought together by this framework is referred to as the current system. However, the current system is not retained by this framework, which maintains only its global properties. Exceptions Standard_DomainError if Density is less than or equal to gp::Resolution().
        	:param Item:
        	:type Item: GProp_GProps
        	:param Density: default value is 1.0
        	:type Density: float
        	:rtype: None
        """
        return _GProp.GProp_GProps_Add(self, *args)


    def CentreOfMass(self, *args) -> "gp_Pnt":
        """
        * Returns the center of mass of the current system. If the gravitational field is uniform, it is the center of gravity. The coordinates returned for the center of mass are expressed in the absolute Cartesian coordinate system.
        	:rtype: gp_Pnt
        """
        return _GProp.GProp_GProps_CentreOfMass(self, *args)


    def __init__(self, *args):
        """
        * The origin (0, 0, 0) of the absolute cartesian coordinate system is used to compute the global properties.
        	:rtype: None
        * The point SystemLocation is used to compute the gobal properties of the system. For more accuracy it is better to define this point closed to the location of the system. For example it could be a point around the centre of mass of the system. This point is referred to as the reference point for this framework. For greater accuracy it is better for the reference point to be close to the location of the system. It can, for example, be a point near the center of mass of the system. At initialization, the framework is empty; i.e. it retains no dimensional information such as mass, or inertia. However, it is now able to bring together global properties of various other systems, whose global properties have already been computed using another framework. To do this, use the function Add to define the components of the system. Use it once per component of the system, and then use the interrogation functions available to access the computed values.
        	:param SystemLocation:
        	:type SystemLocation: gp_Pnt
        	:rtype: None
        """
        _GProp.GProp_GProps_swiginit(self, _GProp.new_GProp_GProps(*args))

    def Mass(self, *args) -> "Standard_Real":
        """
        * Returns the mass of the current system. If no density is attached to the components of the current system the returned value corresponds to : - the total length of the edges of the current system if this framework retains only linear properties, as is the case for example, when using only the LinearProperties function to combine properties of lines from shapes, or - the total area of the faces of the current system if this framework retains only surface properties, as is the case for example, when using only the SurfaceProperties function to combine properties of surfaces from shapes, or - the total volume of the solids of the current system if this framework retains only volume properties, as is the case for example, when using only the VolumeProperties function to combine properties of volumes from solids. Warning A length, an area, or a volume is computed in the current data unit system. The mass of a single object is obtained by multiplying its length, its area or its volume by the given density. You must be consistent with respect to the units used.
        	:rtype: float
        """
        return _GProp.GProp_GProps_Mass(self, *args)


    def MatrixOfInertia(self, *args) -> "gp_Mat":
        """
        * returns the matrix of inertia. It is a symmetrical matrix. The coefficients of the matrix are the quadratic moments of inertia. //! | Ixx Ixy Ixz | matrix = | Ixy Iyy Iyz | | Ixz Iyz Izz | //! The moments of inertia are denoted by Ixx, Iyy, Izz. The products of inertia are denoted by Ixy, Ixz, Iyz. The matrix of inertia is returned in the central coordinate system (G, Gx, Gy, Gz) where G is the centre of mass of the system and Gx, Gy, Gz the directions parallel to the X(1,0,0) Y(0,1,0) Z(0,0,1) directions of the absolute cartesian coordinate system. It is possible to compute the matrix of inertia at another location point using the Huyghens theorem (you can use the method of package GProp : HOperator).
        	:rtype: gp_Mat
        """
        return _GProp.GProp_GProps_MatrixOfInertia(self, *args)


    def MomentOfInertia(self, *args) -> "Standard_Real":
        """
        * computes the moment of inertia of the material system about the axis A.
        	:param A:
        	:type A: gp_Ax1
        	:rtype: float
        """
        return _GProp.GProp_GProps_MomentOfInertia(self, *args)


    def PrincipalProperties(self, *args) -> "GProp_PrincipalProps":
        """
        * Computes the principal properties of inertia of the current system. There is always a set of axes for which the products of inertia of a geometric system are equal to 0; i.e. the matrix of inertia of the system is diagonal. These axes are the principal axes of inertia. Their origin is coincident with the center of mass of the system. The associated moments are called the principal moments of inertia. This function computes the eigen values and the eigen vectors of the matrix of inertia of the system. Results are stored by using a presentation framework of principal properties of inertia (GProp_PrincipalProps object) which may be queried to access the value sought.
        	:rtype: GProp_PrincipalProps
        """
        return _GProp.GProp_GProps_PrincipalProperties(self, *args)


    def RadiusOfGyration(self, *args) -> "Standard_Real":
        """
        * Returns the radius of gyration of the current system about the axis A.
        	:param A:
        	:type A: gp_Ax1
        	:rtype: float
        """
        return _GProp.GProp_GProps_RadiusOfGyration(self, *args)


    def StaticMoments(self, *args) -> "void":
        """
        * Returns Ix, Iy, Iz, the static moments of inertia of the current system; i.e. the moments of inertia about the three axes of the Cartesian coordinate system.
        	:param Ix:
        	:type Ix: float
        	:param Iy:
        	:type Iy: float
        	:param Iz:
        	:type Iz: float
        	:rtype: None
        """
        return _GProp.GProp_GProps_StaticMoments(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_GProps
GProp_GProps.Add = new_instancemethod(_GProp.GProp_GProps_Add, None, GProp_GProps)
GProp_GProps.CentreOfMass = new_instancemethod(_GProp.GProp_GProps_CentreOfMass, None, GProp_GProps)
GProp_GProps.Mass = new_instancemethod(_GProp.GProp_GProps_Mass, None, GProp_GProps)
GProp_GProps.MatrixOfInertia = new_instancemethod(_GProp.GProp_GProps_MatrixOfInertia, None, GProp_GProps)
GProp_GProps.MomentOfInertia = new_instancemethod(_GProp.GProp_GProps_MomentOfInertia, None, GProp_GProps)
GProp_GProps.PrincipalProperties = new_instancemethod(_GProp.GProp_GProps_PrincipalProperties, None, GProp_GProps)
GProp_GProps.RadiusOfGyration = new_instancemethod(_GProp.GProp_GProps_RadiusOfGyration, None, GProp_GProps)
GProp_GProps.StaticMoments = new_instancemethod(_GProp.GProp_GProps_StaticMoments, None, GProp_GProps)
GProp_GProps_swigregister = _GProp.GProp_GProps_swigregister
GProp_GProps_swigregister(GProp_GProps)

class GProp_PEquation(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Box(self, *args) -> "void":
        """
        * Returns the definition of the smallest box which contains all the points analyzed by this framework if, according to the given precision value, the points are considered to be neither coincident, nor collinear and nor coplanar. This box is centered on the barycenter P of the collection of points. Its sides are parallel to the three vectors V1, V2 and V3, the length of which is the length of the box in the corresponding direction. Note: Vectors V1, V2 and V3 are parallel to the three axes of principal inertia of the system composed of the collection of points where each point is of equal mass. Exceptions Standard_NoSuchObject if, according to the given precision, the points analyzed by this framework are considered to be coincident, collinear or coplanar.
        	:param P:
        	:type P: gp_Pnt
        	:param V1:
        	:type V1: gp_Vec
        	:param V2:
        	:type V2: gp_Vec
        	:param V3:
        	:type V3: gp_Vec
        	:rtype: None
        """
        return _GProp.GProp_PEquation_Box(self, *args)


    def __init__(self, *args):
        """
        * Constructs a framework to analyze the collection of points Pnts and computes: - the mean point if the points in question are considered to be coincident within the precision Tol, or - the mean line if they are considered to be collinear within the precision Tol, or - the mean plane if they are considered to be coplanar within the precision Tol, or - the minimal box which contains all the points. Use : - the functions IsPoint, IsLinear, IsPlanar and IsSpace to find the result of the analysis, and - the function Point, Line, Plane or Box to access the computed result.
        	:param Pnts:
        	:type Pnts: TColgp_Array1OfPnt
        	:param Tol:
        	:type Tol: float
        	:rtype: None
        """
        _GProp.GProp_PEquation_swiginit(self, _GProp.new_GProp_PEquation(*args))

    def IsLinear(self, *args) -> "Standard_Boolean":
        """
        * Returns true if, according to the given tolerance, the points analyzed by this framework are colinear. Use the function Line to access the computed result.
        	:rtype: bool
        """
        return _GProp.GProp_PEquation_IsLinear(self, *args)


    def IsPlanar(self, *args) -> "Standard_Boolean":
        """
        * Returns true if, according to the given tolerance, the points analyzed by this framework are coplanar. Use the function Plane to access the computed result.
        	:rtype: bool
        """
        return _GProp.GProp_PEquation_IsPlanar(self, *args)


    def IsPoint(self, *args) -> "Standard_Boolean":
        """
        * Returns true if, according to the given tolerance, the points analyzed by this framework are coincident. Use the function Point to access the computed result.
        	:rtype: bool
        """
        return _GProp.GProp_PEquation_IsPoint(self, *args)


    def IsSpace(self, *args) -> "Standard_Boolean":
        """
        * Returns true if, according to the given tolerance value, the points analyzed by this framework are neither coincident, nor collinear, nor coplanar. Use the function Box to query the smallest box that includes the collection of points.
        	:rtype: bool
        """
        return _GProp.GProp_PEquation_IsSpace(self, *args)


    def Line(self, *args) -> "gp_Lin":
        """
        * Returns the mean line passing near all the points analyzed by this framework if, according to the given precision value, the points are considered to be collinear. Exceptions Standard_NoSuchObject if, according to the given precision, the points analyzed by this framework are considered to be: - coincident, or - not collinear.
        	:rtype: gp_Lin
        """
        return _GProp.GProp_PEquation_Line(self, *args)


    def Plane(self, *args) -> "gp_Pln":
        """
        * Returns the mean plane passing near all the points analyzed by this framework if, according to the given precision, the points are considered to be coplanar. Exceptions Standard_NoSuchObject if, according to the given precision value, the points analyzed by this framework are considered to be: - coincident, or - collinear, or - not coplanar.
        	:rtype: gp_Pln
        """
        return _GProp.GProp_PEquation_Plane(self, *args)


    def Point(self, *args) -> "gp_Pnt":
        """
        * Returns the mean point of all the points analyzed by this framework if, according to the given precision, the points are considered to be coincident. Exceptions Standard_NoSuchObject if, according to the given precision, the points analyzed by this framework are not considered to be coincident.
        	:rtype: gp_Pnt
        """
        return _GProp.GProp_PEquation_Point(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_PEquation
GProp_PEquation.Box = new_instancemethod(_GProp.GProp_PEquation_Box, None, GProp_PEquation)
GProp_PEquation.IsLinear = new_instancemethod(_GProp.GProp_PEquation_IsLinear, None, GProp_PEquation)
GProp_PEquation.IsPlanar = new_instancemethod(_GProp.GProp_PEquation_IsPlanar, None, GProp_PEquation)
GProp_PEquation.IsPoint = new_instancemethod(_GProp.GProp_PEquation_IsPoint, None, GProp_PEquation)
GProp_PEquation.IsSpace = new_instancemethod(_GProp.GProp_PEquation_IsSpace, None, GProp_PEquation)
GProp_PEquation.Line = new_instancemethod(_GProp.GProp_PEquation_Line, None, GProp_PEquation)
GProp_PEquation.Plane = new_instancemethod(_GProp.GProp_PEquation_Plane, None, GProp_PEquation)
GProp_PEquation.Point = new_instancemethod(_GProp.GProp_PEquation_Point, None, GProp_PEquation)
GProp_PEquation_swigregister = _GProp.GProp_PEquation_swigregister
GProp_PEquation_swigregister(GProp_PEquation)

class GProp_PrincipalProps(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def FirstAxisOfInertia(self, *args) -> "gp_Vec const":
        """
        * returns the first axis of inertia. //! if the system has a point of symmetry there is an infinity of solutions. It is not possible to defines the three axis of inertia.
        	:rtype: gp_Vec
        """
        return _GProp.GProp_PrincipalProps_FirstAxisOfInertia(self, *args)


    def __init__(self, *args):
        """
        * creates an undefined PrincipalProps.
        	:rtype: None
        """
        _GProp.GProp_PrincipalProps_swiginit(self, _GProp.new_GProp_PrincipalProps(*args))

    def HasSymmetryAxis(self, *args) -> "Standard_Boolean":
        """
        * returns true if the geometric system has an axis of symmetry. For comparing moments relative tolerance 1.e-10 is used. Usually it is enough for objects, restricted by faces with analitycal geometry.
        	:rtype: bool
        * returns true if the geometric system has an axis of symmetry. aTol is relative tolerance for cheking equality of moments If aTol == 0, relative tolerance is ~ 1.e-16 (Epsilon(I))
        	:param aTol:
        	:type aTol: float
        	:rtype: bool
        """
        return _GProp.GProp_PrincipalProps_HasSymmetryAxis(self, *args)


    def HasSymmetryPoint(self, *args) -> "Standard_Boolean":
        """
        * returns true if the geometric system has a point of symmetry. For comparing moments relative tolerance 1.e-10 is used. Usually it is enough for objects, restricted by faces with analitycal geometry.
        	:rtype: bool
        * returns true if the geometric system has a point of symmetry. aTol is relative tolerance for cheking equality of moments If aTol == 0, relative tolerance is ~ 1.e-16 (Epsilon(I))
        	:param aTol:
        	:type aTol: float
        	:rtype: bool
        """
        return _GProp.GProp_PrincipalProps_HasSymmetryPoint(self, *args)


    def Moments(self, *args) -> "void":
        """
        * Ixx, Iyy and Izz return the principal moments of inertia in the current system. Notes : - If the current system has an axis of symmetry, two of the three values Ixx, Iyy and Izz are equal. They indicate which eigen vectors define an infinity of axes of principal inertia. - If the current system has a center of symmetry, Ixx, Iyy and Izz are equal.
        	:param Ixx:
        	:type Ixx: float
        	:param Iyy:
        	:type Iyy: float
        	:param Izz:
        	:type Izz: float
        	:rtype: None
        """
        return _GProp.GProp_PrincipalProps_Moments(self, *args)


    def RadiusOfGyration(self, *args) -> "void":
        """
        * Returns the principal radii of gyration Rxx, Ryy and Rzz are the radii of gyration of the current system about its three principal axes of inertia. Note that: - If the current system has an axis of symmetry, two of the three values Rxx, Ryy and Rzz are equal. - If the current system has a center of symmetry, Rxx, Ryy and Rzz are equal.
        	:param Rxx:
        	:type Rxx: float
        	:param Ryy:
        	:type Ryy: float
        	:param Rzz:
        	:type Rzz: float
        	:rtype: None
        """
        return _GProp.GProp_PrincipalProps_RadiusOfGyration(self, *args)


    def SecondAxisOfInertia(self, *args) -> "gp_Vec const":
        """
        * returns the second axis of inertia. //! if the system has a point of symmetry or an axis of symmetry the second and the third axis of symmetry are undefined.
        	:rtype: gp_Vec
        """
        return _GProp.GProp_PrincipalProps_SecondAxisOfInertia(self, *args)


    def ThirdAxisOfInertia(self, *args) -> "gp_Vec const":
        """
        * returns the third axis of inertia. This and the above functions return the first, second or third eigen vector of the matrix of inertia of the current system. The first, second and third principal axis of inertia pass through the center of mass of the current system. They are respectively parallel to these three eigen vectors. Note that: - If the current system has an axis of symmetry, any axis is an axis of principal inertia if it passes through the center of mass of the system, and runs parallel to a linear combination of the two eigen vectors of the matrix of inertia, corresponding to the two eigen values which are equal. If the current system has a center of symmetry, any axis passing through the center of mass of the system is an axis of principal inertia. Use the functions HasSymmetryAxis and HasSymmetryPoint to check these particular cases, where the returned eigen vectors define an infinity of principal axis of inertia. - The Moments function can be used to know which of the three eigen vectors corresponds to the two eigen values which are equal. //! if the system has a point of symmetry or an axis of symmetry the second and the third axis of symmetry are undefined.
        	:rtype: gp_Vec
        """
        return _GProp.GProp_PrincipalProps_ThirdAxisOfInertia(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_PrincipalProps
GProp_PrincipalProps.FirstAxisOfInertia = new_instancemethod(_GProp.GProp_PrincipalProps_FirstAxisOfInertia, None, GProp_PrincipalProps)
GProp_PrincipalProps.HasSymmetryAxis = new_instancemethod(_GProp.GProp_PrincipalProps_HasSymmetryAxis, None, GProp_PrincipalProps)
GProp_PrincipalProps.HasSymmetryPoint = new_instancemethod(_GProp.GProp_PrincipalProps_HasSymmetryPoint, None, GProp_PrincipalProps)
GProp_PrincipalProps.Moments = new_instancemethod(_GProp.GProp_PrincipalProps_Moments, None, GProp_PrincipalProps)
GProp_PrincipalProps.RadiusOfGyration = new_instancemethod(_GProp.GProp_PrincipalProps_RadiusOfGyration, None, GProp_PrincipalProps)
GProp_PrincipalProps.SecondAxisOfInertia = new_instancemethod(_GProp.GProp_PrincipalProps_SecondAxisOfInertia, None, GProp_PrincipalProps)
GProp_PrincipalProps.ThirdAxisOfInertia = new_instancemethod(_GProp.GProp_PrincipalProps_ThirdAxisOfInertia, None, GProp_PrincipalProps)
GProp_PrincipalProps_swigregister = _GProp.GProp_PrincipalProps_swigregister
GProp_PrincipalProps_swigregister(GProp_PrincipalProps)

class GProp_CelGProps(GProp_GProps):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None
        :param C:
        	:type C: gp_Circ
        	:param CLocation:
        	:type CLocation: gp_Pnt
        	:rtype: None
        :param C:
        	:type C: gp_Circ
        	:param U1:
        	:type U1: float
        	:param U2:
        	:type U2: float
        	:param CLocation:
        	:type CLocation: gp_Pnt
        	:rtype: None
        :param C:
        	:type C: gp_Lin
        	:param U1:
        	:type U1: float
        	:param U2:
        	:type U2: float
        	:param CLocation:
        	:type CLocation: gp_Pnt
        	:rtype: None
        """
        _GProp.GProp_CelGProps_swiginit(self, _GProp.new_GProp_CelGProps(*args))

    def Perform(self, *args) -> "void":
        """
        :param C:
        	:type C: gp_Circ
        	:param U1:
        	:type U1: float
        	:param U2:
        	:type U2: float
        	:rtype: None
        :param C:
        	:type C: gp_Lin
        	:param U1:
        	:type U1: float
        	:param U2:
        	:type U2: float
        	:rtype: None
        """
        return _GProp.GProp_CelGProps_Perform(self, *args)


    def SetLocation(self, *args) -> "void":
        """
        :param CLocation:
        	:type CLocation: gp_Pnt
        	:rtype: None
        """
        return _GProp.GProp_CelGProps_SetLocation(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_CelGProps
GProp_CelGProps.Perform = new_instancemethod(_GProp.GProp_CelGProps_Perform, None, GProp_CelGProps)
GProp_CelGProps.SetLocation = new_instancemethod(_GProp.GProp_CelGProps_SetLocation, None, GProp_CelGProps)
GProp_CelGProps_swigregister = _GProp.GProp_CelGProps_swigregister
GProp_CelGProps_swigregister(GProp_CelGProps)

class GProp_PGProps(GProp_GProps):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def AddPoint(self, *args) -> "void":
        """
        * Brings together the global properties already retained by this framework with those induced by the point Pnt. Pnt may be the first point of the current system. A point mass is attached to the point Pnt, it is either equal to 1. or to Density.
        	:param P:
        	:type P: gp_Pnt
        	:rtype: None
        * Adds a new point P with its density in the system of points Exceptions Standard_DomainError if the mass value Density is less than gp::Resolution().
        	:param P:
        	:type P: gp_Pnt
        	:param Density:
        	:type Density: float
        	:rtype: None
        """
        return _GProp.GProp_PGProps_AddPoint(self, *args)


    def Barycentre(*args) -> "Standard_Real &":
        """
        * Computes the barycentre of a set of points. The density of the points is defaulted to 1.
        	:param Pnts:
        	:type Pnts: TColgp_Array1OfPnt
        	:rtype: gp_Pnt
        * Computes the barycentre of a set of points. The density of the points is defaulted to 1.
        	:param Pnts:
        	:type Pnts: TColgp_Array2OfPnt
        	:rtype: gp_Pnt
        * Computes the barycentre of a set of points. A density is associated with each point. //! raises if a density is lower or equal to Resolution from package gp. //! Raised if the length of Pnts and the length of Density is not the same.
        	:param Pnts:
        	:type Pnts: TColgp_Array1OfPnt
        	:param Density:
        	:type Density: TColStd_Array1OfReal
        	:param Mass:
        	:type Mass: float
        	:param G:
        	:type G: gp_Pnt
        	:rtype: void
        * Computes the barycentre of a set of points. A density is associated with each point. //! Raised if a density is lower or equal to Resolution from package gp. //! Raised if the length of Pnts and the length of Density is not the same.
        	:param Pnts:
        	:type Pnts: TColgp_Array2OfPnt
        	:param Density:
        	:type Density: TColStd_Array2OfReal
        	:param Mass:
        	:type Mass: float
        	:param G:
        	:type G: gp_Pnt
        	:rtype: void
        """
        return _GProp.GProp_PGProps_Barycentre(*args)

    Barycentre = staticmethod(Barycentre)

    def __init__(self, *args):
        """
        * Initializes a framework to compute global properties on a set of points. The point relative to which the inertia of the system is computed will be the origin (0, 0, 0) of the absolute Cartesian coordinate system. At initialization, the framework is empty, i.e. it retains no dimensional information such as mass and inertia. It is, however, now able to keep global properties of a set of points while new points are added using the AddPoint function. The set of points whose global properties are brought together by this framework will then be referred to as the current system. The current system is, however, not kept by this framework, which only keeps that system's global properties. Note that the current system may be more complex than a set of points.
        	:rtype: None
        * computes the global properties of the system of points Pnts. The density of the points are defaulted to all being 1
        	:param Pnts:
        	:type Pnts: TColgp_Array1OfPnt
        	:rtype: None
        * computes the global properties of the system of points Pnts. The density of the points are defaulted to all being 1
        	:param Pnts:
        	:type Pnts: TColgp_Array2OfPnt
        	:rtype: None
        * computes the global properties of the system of points Pnts. A density is associated with each point. //! raises if a density is lower or equal to Resolution from package gp. //! raises if the length of Pnts and the length of Density is not the same.
        	:param Pnts:
        	:type Pnts: TColgp_Array1OfPnt
        	:param Density:
        	:type Density: TColStd_Array1OfReal
        	:rtype: None
        * computes the global properties of the system of points Pnts. A density is associated with each point. //! Raised if a density is lower or equal to Resolution from package gp. //! Raised if the length of Pnts and the length of Density is not the same.
        	:param Pnts:
        	:type Pnts: TColgp_Array2OfPnt
        	:param Density:
        	:type Density: TColStd_Array2OfReal
        	:rtype: None
        """
        _GProp.GProp_PGProps_swiginit(self, _GProp.new_GProp_PGProps(*args))

    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_PGProps
GProp_PGProps.AddPoint = new_instancemethod(_GProp.GProp_PGProps_AddPoint, None, GProp_PGProps)
GProp_PGProps_swigregister = _GProp.GProp_PGProps_swigregister
GProp_PGProps_swigregister(GProp_PGProps)

def GProp_PGProps_Barycentre(*args) -> "Standard_Real &":
    """
    * Computes the barycentre of a set of points. The density of the points is defaulted to 1.
    	:param Pnts:
    	:type Pnts: TColgp_Array1OfPnt
    	:rtype: gp_Pnt
    * Computes the barycentre of a set of points. The density of the points is defaulted to 1.
    	:param Pnts:
    	:type Pnts: TColgp_Array2OfPnt
    	:rtype: gp_Pnt
    * Computes the barycentre of a set of points. A density is associated with each point. //! raises if a density is lower or equal to Resolution from package gp. //! Raised if the length of Pnts and the length of Density is not the same.
    	:param Pnts:
    	:type Pnts: TColgp_Array1OfPnt
    	:param Density:
    	:type Density: TColStd_Array1OfReal
    	:param Mass:
    	:type Mass: float
    	:param G:
    	:type G: gp_Pnt
    	:rtype: void
    * Computes the barycentre of a set of points. A density is associated with each point. //! Raised if a density is lower or equal to Resolution from package gp. //! Raised if the length of Pnts and the length of Density is not the same.
    	:param Pnts:
    	:type Pnts: TColgp_Array2OfPnt
    	:param Density:
    	:type Density: TColStd_Array2OfReal
    	:param Mass:
    	:type Mass: float
    	:param G:
    	:type G: gp_Pnt
    	:rtype: void
    """
    return _GProp.GProp_PGProps_Barycentre(*args)

class GProp_SelGProps(GProp_GProps):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None
        :param S:
        	:type S: gp_Cylinder
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:param SLocation:
        	:type SLocation: gp_Pnt
        	:rtype: None
        :param S:
        	:type S: gp_Cone
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:param SLocation:
        	:type SLocation: gp_Pnt
        	:rtype: None
        :param S:
        	:type S: gp_Sphere
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param SLocation:
        	:type SLocation: gp_Pnt
        	:rtype: None
        :param S:
        	:type S: gp_Torus
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param SLocation:
        	:type SLocation: gp_Pnt
        	:rtype: None
        """
        _GProp.GProp_SelGProps_swiginit(self, _GProp.new_GProp_SelGProps(*args))

    def Perform(self, *args) -> "void":
        """
        :param S:
        	:type S: gp_Cylinder
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:rtype: None
        :param S:
        	:type S: gp_Cone
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:rtype: None
        :param S:
        	:type S: gp_Sphere
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:rtype: None
        :param S:
        	:type S: gp_Torus
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:rtype: None
        """
        return _GProp.GProp_SelGProps_Perform(self, *args)


    def SetLocation(self, *args) -> "void":
        """
        :param SLocation:
        	:type SLocation: gp_Pnt
        	:rtype: None
        """
        return _GProp.GProp_SelGProps_SetLocation(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_SelGProps
GProp_SelGProps.Perform = new_instancemethod(_GProp.GProp_SelGProps_Perform, None, GProp_SelGProps)
GProp_SelGProps.SetLocation = new_instancemethod(_GProp.GProp_SelGProps_SetLocation, None, GProp_SelGProps)
GProp_SelGProps_swigregister = _GProp.GProp_SelGProps_swigregister
GProp_SelGProps_swigregister(GProp_SelGProps)

class GProp_VelGProps(GProp_GProps):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None
        :param S:
        	:type S: gp_Cylinder
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:param VLocation:
        	:type VLocation: gp_Pnt
        	:rtype: None
        :param S:
        	:type S: gp_Cone
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:param VLocation:
        	:type VLocation: gp_Pnt
        	:rtype: None
        :param S:
        	:type S: gp_Sphere
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param VLocation:
        	:type VLocation: gp_Pnt
        	:rtype: None
        :param S:
        	:type S: gp_Torus
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param VLocation:
        	:type VLocation: gp_Pnt
        	:rtype: None
        """
        _GProp.GProp_VelGProps_swiginit(self, _GProp.new_GProp_VelGProps(*args))

    def Perform(self, *args) -> "void":
        """
        :param S:
        	:type S: gp_Cylinder
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:rtype: None
        :param S:
        	:type S: gp_Cone
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:param Z1:
        	:type Z1: float
        	:param Z2:
        	:type Z2: float
        	:rtype: None
        :param S:
        	:type S: gp_Sphere
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:rtype: None
        :param S:
        	:type S: gp_Torus
        	:param Teta1:
        	:type Teta1: float
        	:param Teta2:
        	:type Teta2: float
        	:param Alpha1:
        	:type Alpha1: float
        	:param Alpha2:
        	:type Alpha2: float
        	:rtype: None
        """
        return _GProp.GProp_VelGProps_Perform(self, *args)


    def SetLocation(self, *args) -> "void":
        """
        :param VLocation:
        	:type VLocation: gp_Pnt
        	:rtype: None
        """
        return _GProp.GProp_VelGProps_SetLocation(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _GProp.delete_GProp_VelGProps
GProp_VelGProps.Perform = new_instancemethod(_GProp.GProp_VelGProps_Perform, None, GProp_VelGProps)
GProp_VelGProps.SetLocation = new_instancemethod(_GProp.GProp_VelGProps_SetLocation, None, GProp_VelGProps)
GProp_VelGProps_swigregister = _GProp.GProp_VelGProps_swigregister
GProp_VelGProps_swigregister(GProp_VelGProps)



