# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
Plugin module, see official documentation at
https://www.opencascade.com/doc/occt-7.4.0/refman/html/package_plugin.html
"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _Plugin.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Plugin')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Plugin')
    _Plugin = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Plugin', [dirname(__file__)])
        except ImportError:
            import _Plugin
            return _Plugin
        try:
            _mod = imp.load_module('_Plugin', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Plugin = swig_import_helper()
    del swig_import_helper
else:
    import _Plugin
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Plugin.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_Plugin.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_Plugin.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_Plugin.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_Plugin.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_Plugin.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_Plugin.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_Plugin.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_Plugin.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_Plugin.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_Plugin.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_Plugin.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_Plugin.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_Plugin.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_Plugin.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_Plugin.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_Plugin.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _Plugin.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string


def process_exception(error: 'Standard_Failure const &', method_name: 'std::string', class_name: 'std::string') -> "void":
    return _Plugin.process_exception(error, method_name, class_name)
process_exception = _Plugin.process_exception

from six import with_metaclass
import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

import OCC.Core.Standard
import OCC.Core.NCollection
class Plugin_MapOfFunctions(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Plugin.Plugin_MapOfFunctions_swiginit(self, _Plugin.new_Plugin_MapOfFunctions(*args))
    __swig_destroy__ = _Plugin.delete_Plugin_MapOfFunctions
Plugin_MapOfFunctions.begin = new_instancemethod(_Plugin.Plugin_MapOfFunctions_begin, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.end = new_instancemethod(_Plugin.Plugin_MapOfFunctions_end, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.cbegin = new_instancemethod(_Plugin.Plugin_MapOfFunctions_cbegin, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.cend = new_instancemethod(_Plugin.Plugin_MapOfFunctions_cend, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Exchange = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Exchange, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Assign = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Assign, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Set = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Set, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.ReSize = new_instancemethod(_Plugin.Plugin_MapOfFunctions_ReSize, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Bind = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Bind, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Bound = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Bound, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.IsBound = new_instancemethod(_Plugin.Plugin_MapOfFunctions_IsBound, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.UnBind = new_instancemethod(_Plugin.Plugin_MapOfFunctions_UnBind, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Seek = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Seek, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Find = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Find, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.ChangeSeek = new_instancemethod(_Plugin.Plugin_MapOfFunctions_ChangeSeek, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.ChangeFind = new_instancemethod(_Plugin.Plugin_MapOfFunctions_ChangeFind, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.__call__ = new_instancemethod(_Plugin.Plugin_MapOfFunctions___call__, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Clear = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Clear, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions.Size = new_instancemethod(_Plugin.Plugin_MapOfFunctions_Size, None, Plugin_MapOfFunctions)
Plugin_MapOfFunctions_swigregister = _Plugin.Plugin_MapOfFunctions_swigregister
Plugin_MapOfFunctions_swigregister(Plugin_MapOfFunctions)



